name: Test Brew formulas

on:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  test-formulas:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
        formula:
          - alibuild
          - alice-build-machine
          - o2-full-deps
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Add tap
        run: |
          brew tap sergio/system-deps ${{ github.workspace }}
      
      - name: Test install formula
        run: |
          brew install ${{ matrix.formula }}
      
      - name: Cleanup
        run: |
          brew uninstall ${{ matrix.formula }} || true
          brew untap sergio/system-deps || true
